### ISSUE TITLE
Dots centered

### ISSUE THREAD

**Issue by JeminiBo** [felire/react-native-animated-dots-carousel#2]
Hey @felire , how i can always center dots, maybe you can help me with it?
Initially they not center:
![image](https://github.com/felire/react-native-animated-dots-carousel/assets/30500640/bdf9daf7-6948-4f19-9378-938095846108)
I need something like that:
![image](https://github.com/felire/react-native-animated-dots-carousel/assets/30500640/d325df2a-6976-4fd2-ab17-3da82699b6b1)

**Comment by dieptang** [comment]
+1. Yes, thats need.

**Comment by felire** [comment]
@JeminiBo 

Hey! The dots container have empty spaces in order to have space to show the smaller dots when it is needed. So I think you will have to adjust the text you want to show to the dots container. In the image I am seeing, it is on the left of the container.

So the issue would be that there is no a good way to show a text or something with the dots and have it centered?

Could you share your code so I can have a better understanding?

**Comment by felire** [comment]
Closing cause inactivity
